import jsPDF from "jspdf";
import * as pdfjsLib from "pdfjs-dist";

// Set worker path for PDF.js
pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js`;

export const generatePDF = (content: string, title: string = "JonzTech AI Document") => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  
  // Add title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, margin, margin + 10);
  
  // Add date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, margin, margin + 20);
  
  // Add horizontal line
  doc.setDrawColor(0, 150, 136);
  doc.line(margin, margin + 25, pageWidth - margin, margin + 25);
  
  // Add content
  doc.setFontSize(12);
  let yPosition = margin + 35;
  
  const lines = doc.splitTextToSize(content, maxWidth);
  
  for (const line of lines) {
    if (yPosition > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
    doc.text(line, margin, yPosition);
    yPosition += 7;
  }
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by JonzTech AI`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }
  
  return doc;
};

export const downloadPDF = (content: string, filename: string = "jonztech-ai-document.pdf") => {
  const doc = generatePDF(content);
  doc.save(filename);
};

export const createPDFBlobUrl = (content: string, title?: string): string => {
  const doc = generatePDF(content, title);
  const blob = doc.output('blob');
  return URL.createObjectURL(blob);
};

export const extractTextFromPDF = async (file: File): Promise<string> => {
  try {
    const arrayBuffer = await file.arrayBuffer();
    const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
    
    let fullText = "";
    
    for (let i = 1; i <= pdf.numPages; i++) {
      const page = await pdf.getPage(i);
      const textContent = await page.getTextContent();
      const pageText = textContent.items
        .map((item: any) => item.str)
        .join(" ");
      fullText += `\n--- Page ${i} ---\n${pageText}`;
    }
    
    return fullText.trim();
  } catch (error) {
    console.error("Error extracting PDF text:", error);
    throw new Error("Failed to extract text from PDF");
  }
};